"""add cascade delete

Revision ID: f7c48c06424b
Revises: fc6224d77d95
Create Date: 2025-08-06 15:47:31.131973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7c48c06424b"
down_revision: Union[str, Sequence[str], None] = "fc6224d77d95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ozon_product_characteristics_unique_id_fkey"),
        "ozon_product_characteristics",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "ozon_product_characteristics",
        "ozon_search_match",
        ["unique_id"],
        ["unique_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("ozon_product_top_unique_id_fkey"), "ozon_product_top", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "ozon_product_top",
        "ozon_search_match",
        ["unique_id"],
        ["unique_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("ozon_url_products_unique_id_fkey"),
        "ozon_url_products",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "ozon_url_products",
        "ozon_search_match",
        ["unique_id"],
        ["unique_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ozon_url_products", type_="foreignkey")
    op.create_foreign_key(
        op.f("ozon_url_products_unique_id_fkey"),
        "ozon_url_products",
        "ozon_search_match",
        ["unique_id"],
        ["unique_id"],
    )
    op.drop_constraint(None, "ozon_product_top", type_="foreignkey")
    op.create_foreign_key(
        op.f("ozon_product_top_unique_id_fkey"),
        "ozon_product_top",
        "ozon_search_match",
        ["unique_id"],
        ["unique_id"],
    )
    op.drop_constraint(None, "ozon_product_characteristics", type_="foreignkey")
    op.create_foreign_key(
        op.f("ozon_product_characteristics_unique_id_fkey"),
        "ozon_product_characteristics",
        "ozon_search_match",
        ["unique_id"],
        ["unique_id"],
    )
    # ### end Alembic commands ###
